name: extraction
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - arrow-cpp=17.0.0=h865e1df_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - blas=1.0=openblas
  - bokeh=3.6.0=py311h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.12.31=h06a4308_0
  - click=8.1.7=py311h06a4308_0
  - cloudpickle=3.0.0=py311h06a4308_0
  - comm=0.2.1=py311h06a4308_0
  - cytoolz=0.12.2=py311h5eee18b_0
  - dask-core=2024.8.2=py311h06a4308_0
  - dask-expr=1.1.13=py311h06a4308_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - distributed=2024.8.2=py311h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icu=73.1=h6a678d5_0
  - ipykernel=6.28.0=py311h06a4308_0
  - ipython=8.20.0=py311h06a4308_0
  - jedi=0.18.1=py311h06a4308_1
  - jinja2=3.1.4=py311h06a4308_1
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.0=py311h06a4308_0
  - jupyter_core=5.5.0=py311h06a4308_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcurl=8.11.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=13.2.0=h77fa898_7
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=13.2.0=h77fa898_7
  - libgrpc=1.62.2=h2d74bed_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - locket=1.0.0=py311h06a4308_0
  - lz4=4.3.2=py311h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - msgpack-python=1.0.3=py311hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - numexpr=2.10.1=py311hd28fd6d_0
  - numpy=1.26.4=py311h24aa872_0
  - numpy-base=1.26.4=py311hbfb1bba_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.0=hd590300_0
  - orc=2.0.1=h2d29ad5_0
  - packaging=23.2=py311h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pip=24.0=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=17.0.0=py311ha02d727_0
  - pygments=2.15.1=py311h06a4308_1
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.9=h955ad1f_0
  - python-dateutil=2.9.0post0=py311h06a4308_0
  - python-lmdb=1.6.2=py311h6a678d5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py311h06a4308_0
  - pyzmq=25.1.2=py311h6a678d5_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - s2n=1.3.27=hdbd6064_0
  - setuptools=69.5.1=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.3.3=py311h5eee18b_0
  - traitlets=5.7.1=py311h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.43.0=py311h06a4308_0
  - xyzservices=2022.9.0=py311h06a4308_1
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zict=3.0.0=py311h06a4308_0
  - zipp=3.21.0=py311h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - alabaster==0.7.16
      - annotated-types==0.6.0
      - ansi2html==1.9.2
      - anyio==4.9.0
      - app-model==0.2.7
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - blinker==1.9.0
      - build==1.2.1
      - cachey==0.2.1
      - celluloid==0.2.0
      - certifi==2024.2.2
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - contourpy==1.2.1
      - cowpy==1.1.5
      - cupy-cuda12x==13.2.0
      - cycler==0.12.1
      - dash==3.0.4
      - dask==2024.5.1
      - dask-image==2025.11.0
      - defusedxml==0.7.1
      - dill==0.4.0
      - docstring-parser==0.16
      - docutils==0.21.2
      - fasteners==0.19
      - fastjsonschema==2.21.1
      - fastrlock==0.8.2
      - flask==3.0.3
      - fonttools==4.51.0
      - fqdn==1.5.1
      - freetype-py==2.4.0
      - frozenlist==1.6.0
      - fsspec==2024.5.0
      - hsluv==5.0.4
      - idna==3.7
      - imageio==2.34.1
      - imageio-ffmpeg==0.6.0
      - imagesize==1.4.1
      - importlib-metadata==7.1.0
      - in-n-out==0.2.1
      - ipyevents==2.0.2
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - joblib==1.4.2
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-dash==0.4.2
      - jupyter-events==0.12.0
      - jupyter-server==2.16.0
      - jupyter-server-proxy==4.4.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab-dash==0.1.0a3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - llvmlite==0.42.0
      - magicgui==0.8.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - mistune==3.1.3
      - multidict==6.4.4
      - multipledispatch==1.0.0
      - napari==0.4.19.post1
      - napari-console==0.0.9
      - napari-plugin-engine==0.2.0
      - napari-plugin-manager==0.1.0a2
      - napari-svg==0.1.10
      - narwhals==1.40.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nd2==0.10.1
      - nd2-extractor==0.1.0
      - nd2reader==3.3.0
      - ndstorage==0.1.18
      - networkx==3.3
      - npe2==0.7.5
      - numba==0.59.1
      - numcodecs==0.12.1
      - numpydoc==1.7.0
      - ome-types==0.5.1.post1
      - opencv-python-headless==4.12.0.88
      - overrides==7.7.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - partd==1.4.2
      - patsy==0.5.6
      - pillow==10.3.0
      - pims==0.7
      - pims-nd2==1.1
      - pint==0.23
      - plotly==6.1.1
      - pooch==1.8.1
      - prometheus-client==0.22.0
      - propcache==0.3.1
      - psygnal==0.11.1
      - pyconify==0.1.6
      - pycparser==2.22
      - pydantic==2.7.1
      - pydantic-compat==0.1.2
      - pydantic-core==2.18.2
      - pyopengl==3.1.7
      - pyparsing==3.1.2
      - pyperclip==1.9.0
      - pyproject-hooks==1.1.0
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pystackreg==0.2.7
      - python-graphviz==0.20.3
      - python-json-logger==3.3.0
      - pyyaml==6.0.1
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - read-roi==1.6.0
      - referencing==0.35.1
      - requests==2.32.0
      - resource-backed-dask-array==0.1.0
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - roifile==2025.5.10
      - rpds-py==0.18.1
      - scienceplots==2.1.1
      - scikit-image==0.23.2
      - scikit-learn==1.5.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - shellingham==1.5.4
      - simpervisor==1.0.0
      - slicerator==1.1.0
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.7
      - sphinx==7.3.7
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - statannotations==0.7.1
      - statsmodels==0.14.2
      - superqt==0.6.6
      - tabulate==0.9.0
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2024.5.10
      - tinycss2==1.4.0
      - tomli-w==1.0.0
      - toolz==0.12.1
      - tqdm==4.66.4
      - tqdm-joblib==0.0.4
      - triangle==20230923
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.1
      - vispy==0.14.2
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.10
      - wrapt==1.16.0
      - xmltodict==0.14.2
      - xsdata==24.3.1
      - yarl==1.20.0
      - zarr==2.18.1
prefix: /home/ka537/miniconda3/envs/extraction
