name: omnipose
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py310h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.2.1=py310h06a4308_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.28.0=py310h06a4308_0
  - ipython=8.20.0=py310h06a4308_0
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.1.3=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.0=py310h06a4308_0
  - jupyter_core=5.5.0=py310h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py310h06a4308_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_1
  - packaging=23.2=py310h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.3.0=py310h5eee18b_0
  - pip=24.0=py310h06a4308_0
  - platformdirs=3.10.0=py310h06a4308_0
  - prompt-toolkit=3.0.43=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py310h06a4308_1
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.12=h955ad1f_0
  - python-dateutil=2.9.0post0=py310h06a4308_0
  - pytorch=2.3.0=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h5eee18b_0
  - pyzmq=25.1.2=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py310h06a4308_1
  - setuptools=69.5.1=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchtriton=2.3.0=py310
  - torchvision=0.18.0=py310_cu118
  - tornado=6.3.3=py310h5eee18b_0
  - traitlets=5.7.1=py310h06a4308_0
  - typing_extensions=4.11.0=py310h06a4308_0
  - urllib3=2.2.1=py310h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - alabaster==0.7.16
      - annotated-types==0.7.0
      - app-model==0.2.7
      - appdirs==1.4.4
      - asciitree==0.3.3
      - attrs==23.2.0
      - babel==2.15.0
      - build==1.2.1
      - cachey==0.2.1
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - dask==2024.5.1
      - docstring-parser==0.16
      - docutils==0.21.2
      - edt==2.4.0
      - fasteners==0.19
      - fastremap==1.14.1
      - fonttools==4.51.0
      - freetype-py==2.4.0
      - fsspec==2024.5.0
      - heapdict==1.0.1
      - hsluv==5.0.4
      - igraph==0.11.5
      - imageio==2.34.1
      - imagesize==1.4.1
      - importlib-metadata==7.1.0
      - in-n-out==0.2.1
      - joblib==1.4.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - llvmlite==0.42.0
      - locket==1.0.0
      - magicgui==0.8.2
      - mahotas==1.4.15
      - markdown-it-py==3.0.0
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - mgen==1.2.1
      - napari==0.4.19.post1
      - napari-console==0.0.9
      - napari-plugin-engine==0.2.0
      - napari-svg==0.1.10
      - natsort==8.4.0
      - ncolor==1.2.1
      - npe2==0.7.5
      - numba==0.59.1
      - numcodecs==0.12.1
      - numpydoc==1.7.0
      - omnipose==1.0.6
      - opencv-python-headless==4.9.0.80
      - pandas==2.2.2
      - partd==1.4.2
      - pbr==6.0.0
      - peakdetect==1.2
      - pint==0.23
      - pooch==1.8.1
      - psygnal==0.11.1
      - pyconify==0.1.6
      - pydantic==2.7.1
      - pydantic-compat==0.1.2
      - pydantic-core==2.18.2
      - pyopengl==3.1.7
      - pyparsing==3.1.2
      - pyproject-hooks==1.1.0
      - pytorch-ranger==0.1.1
      - pytz==2024.1
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - referencing==0.35.1
      - rich==13.7.1
      - rpds-py==0.18.1
      - scikit-image==0.23.2
      - scikit-learn==1.5.0
      - scipy==1.11.4
      - shellingham==1.5.4
      - snowballstemmer==2.2.0
      - sphinx==7.3.7
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - superqt==0.6.6
      - tabulate==0.9.0
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tifffile==2024.5.10
      - tomli==2.0.1
      - tomli-w==1.0.0
      - toolz==0.12.1
      - torch-optimizer==0.3.0
      - torchvf==0.1.4
      - tqdm==4.66.4
      - tqdm-joblib==0.0.4
      - typer==0.12.3
      - tzdata==2024.1
      - vispy==0.14.2
      - wrapt==1.16.0
      - zarr==2.18.3
      - zipp==3.18.2
prefix: /home/ka537/miniconda3/envs/omnipose
